language: java
services:
  - docker
env:
  - CHANGE_MINIKUBE_NONE_USER=true
before_script:
  - unset _JAVA_OPTIONS
  - cd finish
  - chmod +x ../scripts/travisTest.sh
script: 
  - sudo mount --make-rshared /
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
  - wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
  - chmod +x minikube
  - sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
  - sudo minikube start --vm-driver=none --bootstrapper=localkube
  - ../scripts/travisTest.sh
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: doKR84X5pdlj9kPdwTXWf7cHuDBUJoG9qqFlhFGxi/e8aQ5jJ6HMer9wb8MwhYzJfaDRLNQtseX8bmot68igdAAGxGH5pCC5Kj+cNY7J2geKz3RuETskk13diXxcB2pztlYm9KjiQzg52wMeJ5A59uRkYGBGJGo0vW4+Ill5iPUeac4cNSKajxspdxHt/lKufjTb0GdhwUJYH3BMM46JeRb36HhRSHnwehPyYTF58q4SiJWebM7Y8e5rKNe/jEotjPVgkC/KUy1m1N2LP3yjouXKP3xHLs8Qtzabe59wUMjbGZP3Hse+V0fTeWSwvPldlC1zd3qynbjqkh7opV0JFL9XoCJiFDQhGM9c91c9vBz2+iBMJxWVXMnQ+d9/OBUen8YtPMBefuHflMlxYKRSjlShkX5ZzoOaqJhnL+60lRocM7Va/uPVcxSj8TiuFuI/8DWtpEq22GKOUBWj8Y5/7YepXMV7q8eyNuD3J0L2h4Pgvs9xu2pv7tEEgMRdGZ5nLXzkVoZjeHDUMGc6mZPGyff324ajnDlxifzm/5EWUjO2orWX/ic+ZiDkwMRwWx/EfmqjKzske7C631OkHwuodVvBfluYB6bJZzNP2bV5sb3trtFQYnP1Bqx2AJNlPQwZ2/Sm1VWWcHi0E97jriF07NNTB5pEJPwQCRQt0bq5rW4= 
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
